pipeline {
    agent any

    stages {

        stage('Unit Tests - Backend') {
            steps {
                script {
                    echo "Running Go unit tests..."

                    // Run tests inside Docker container
                    sh """
                        docker run --rm \
                        -v \$PWD/bugtracker-backend:/app \
                        -w /app \
                        snakee/golang-junit:1.21 \
                        go test ./... -v
                    """
                }
            }
        }

    }

}
