name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:

  # ---------------------------
  # BACKEND UNIT TESTS
  # ---------------------------
  unit-tests-backend:
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.test-backend.outputs.report }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache-dependency-path: bugtracker-backend/go.sum

      - name: Install go-junit-report
        run: |
          go install github.com/jstemmer/go-junit-report@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Execute Backend Unit Tests
        id: test-backend
        working-directory: ./bugtracker-backend
        run: |
          go test -json -coverprofile=coverage.out -covermode=atomic ./...
          go tool cover -func=coverage.out > coverage.txt

          echo "## Go Test Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat coverage.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

          echo "report<<EOP" >> $GITHUB_OUTPUT
          cat coverage.txt >> $GITHUB_OUTPUT
          echo "EOP" >> $GITHUB_OUTPUT

          go test -v ./... 2>&1 | go-junit-report > test-results.xml

      - name: Publish Backend Unit Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Backend Unit Tests Report
          path: bugtracker-backend/test-results.xml
          reporter: java-junit



  # ---------------------------
  # FRONTEND UNIT TESTS
  # ---------------------------
  unit-tests-frontend:
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.test-frontend.outputs.report }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: bugtracker-frontend/package-lock.json

      - name: Run Frontend Unit Tests
        id: test-frontend
        working-directory: ./bugtracker-frontend
        run: |
          npm ci
          npm test | tee full_output.txt
          
          echo "## Frontend Test Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat full_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

          echo "report<<EOP" >> $GITHUB_OUTPUT
          cat full_output.txt >> $GITHUB_OUTPUT
          echo "EOP" >> $GITHUB_OUTPUT

      - name: Publish Frontend Unit Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Frontend Unit Tests Report
          path: bugtracker-frontend/test-results.xml
          reporter: jest-junit



  # ---------------------------
  # POST COVERAGE COMMENT
  # ---------------------------
  create-coverage-comment:
    if: github.event_name == 'pull_request'
    needs: [unit-tests-backend, unit-tests-frontend]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Create Backend Coverage Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Backend Test Coverage Report
            ${{ needs.unit-tests-backend.outputs.coverage }}

      - name: Create Frontend Coverage Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Frontend Test Coverage Report
            ${{ needs.unit-tests-frontend.outputs.coverage }}



  # ------------------------------------------------------
  # API / E2E / Performance TESTS
  # ------------------------------------------------------
  api-e2e-perf-tests:
    needs: [unit-tests-backend, unit-tests-frontend]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Playwright Browsers + Dependencies
        run: |
          npm i -g playwright
          playwright install --with-deps

      - name: Fix Docker Compose plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      - name: Launch Application
        run: |
          docker compose up --build -d
          npx wait-on http://localhost:10000/api/health

      # -----------------------
      # API Tests
      # -----------------------
      - name: Run API tests
        working-directory: ./tests-api
        run: |
          npm ci
          playwright install --with-deps
          npx playwright test

      # -----------------------
      # UI E2E Tests
      # -----------------------
      - name: Run E2E Tests
        working-directory: ./tests-e2e  
        env:
          CI: "1"
          PLAYWRIGHT_TEST_BASE_URL: "http://localhost:3000"
        run: |
          npm ci
          playwright install --with-deps
          npx playwright test

      # -----------------------
      # K6 Performance Test
      # -----------------------
      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run Performance Test
        uses: grafana/run-k6-action@v1
        with:
          path: tests-perf/script.js
          flags: --out json=summary.json  

      - name: Shut down Application
        run: docker compose down    

      # Uploading reports
      - name: Upload API test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: ./tests-api/test-results/

      - name: Upload API playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-playwright-report
          path: ./tests-api/playwright-report/

      - name: Upload E2E playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-playwright-report
          path: ./tests-e2e/playwright-report/

      - name: Upload Performance Raw Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Performance-raw-results
          path: summary.json

      - name: Publish API Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: API Tests Report
          path: ./tests-api/test-results/*.xml
          reporter: jest-junit

      - name: Publish E2E Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: E2E Tests Report
          path: ./tests-e2e/test-results/*.xml
          reporter: jest-junit 



  # ---------------------------
  # BACKEND DEPLOY TO RENDER
  # ---------------------------
  deploy-backend:
    needs: [api-e2e-perf-tests]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend to Render
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{
              secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"clearCache": false}' \
            https://api.render.com/v1/services/${{
              secrets.RENDER_BACKEND_SERVICE_ID }}/deploys



  # ---------------------------
  # FRONTEND DEPLOY TO NETLIFY
  # ---------------------------
  deploy-frontend:
    needs: [api-e2e-perf-tests]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps & build frontend
        working-directory: ./bugtracker-frontend
        run: |
          npm ci
          npm run build

      - name: Deploy to Netlify
        uses: netlify/actions/cli@v3
        with:
          args: deploy --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
